# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nngpCovariance__new <- function(formula_, data_, colnames_, T_, m_, gptr_) {
    .Call(`_rts2_nngpCovariance__new`, formula_, data_, colnames_, T_, m_, gptr_)
}

GridData__new <- function(x_, t_) {
    .Call(`_rts2_GridData__new`, x_, t_)
}

GridData_nn__new <- function(x_, t_, m_) {
    .Call(`_rts2_GridData_nn__new`, x_, t_, m_)
}

RegionData__new <- function(n_cell_, cell_id_, q_weights_, N_, T_) {
    .Call(`_rts2_RegionData__new`, n_cell_, cell_id_, q_weights_, N_, T_)
}

Model_ar_lp__new <- function(formula_, data_, grid_data_, colnames_, beta_, theta_, T) {
    .Call(`_rts2_Model_ar_lp__new`, formula_, data_, grid_data_, colnames_, beta_, theta_, T)
}

Model_nngp_lp__new <- function(formula_, data_, grid_data_, colnames_, beta_, theta_, T, m, gptr_) {
    .Call(`_rts2_Model_nngp_lp__new`, formula_, data_, grid_data_, colnames_, beta_, theta_, T, m, gptr_)
}

Model_hsgp_lp__new <- function(formula_, data_, grid_data_, colnames_, beta_, theta_, T, m, L_) {
    .Call(`_rts2_Model_hsgp_lp__new`, formula_, data_, grid_data_, colnames_, beta_, theta_, T, m, L_)
}

Model_ar_region_grid__new <- function(formula_region_, formula_grid_, data_region_, data_grid_, colnames_region_, colnames_grid_, beta_, theta_, rptr_, T) {
    .Call(`_rts2_Model_ar_region_grid__new`, formula_region_, formula_grid_, data_region_, data_grid_, colnames_region_, colnames_grid_, beta_, theta_, rptr_, T)
}

Model_nngp_region_grid__new <- function(formula_region_, formula_grid_, data_region_, data_grid_, colnames_region_, colnames_grid_, beta_, theta_, rptr_, gptr_, T, m) {
    .Call(`_rts2_Model_nngp_region_grid__new`, formula_region_, formula_grid_, data_region_, data_grid_, colnames_region_, colnames_grid_, beta_, theta_, rptr_, gptr_, T, m)
}

Model_hsgp_region_grid__new <- function(formula_region_, formula_grid_, data_region_, data_grid_, colnames_region_, colnames_grid_, beta_, theta_, rptr_, T, m, L_) {
    .Call(`_rts2_Model_hsgp_region_grid__new`, formula_region_, formula_grid_, data_region_, data_grid_, colnames_region_, colnames_grid_, beta_, theta_, rptr_, T, m, L_)
}

Model_ar_region__new <- function(formula_, data_, grid_data_, colnames_, beta_, theta_, T, rptr_) {
    .Call(`_rts2_Model_ar_region__new`, formula_, data_, grid_data_, colnames_, beta_, theta_, T, rptr_)
}

Model_nngp_region__new <- function(formula_, data_, grid_data_, colnames_, beta_, theta_, T, m, rptr_, gptr_) {
    .Call(`_rts2_Model_nngp_region__new`, formula_, data_, grid_data_, colnames_, beta_, theta_, T, m, rptr_, gptr_)
}

Model_hsgp_region__new <- function(formula_, data_, grid_data_, colnames_, beta_, theta_, T, m, rptr_, L_) {
    .Call(`_rts2_Model_hsgp_region__new`, formula_, data_, grid_data_, colnames_, beta_, theta_, T, m, rptr_, L_)
}

GridData__NN <- function(ptr_) {
    .Call(`_rts2_GridData__NN`, ptr_)
}

GridData__gen_NN <- function(ptr_, m_) {
    invisible(.Call(`_rts2_GridData__gen_NN`, ptr_, m_))
}

rtsModel__set_y <- function(xp, y_, covtype_, lptype_) {
    invisible(.Call(`_rts2_rtsModel__set_y`, xp, y_, covtype_, lptype_))
}

rtsModel__set_offset <- function(xp, offset_, covtype_, lptype_) {
    invisible(.Call(`_rts2_rtsModel__set_offset`, xp, offset_, covtype_, lptype_))
}

rtsModel__set_weights <- function(xp, weights_, covtype_, lptype_) {
    invisible(.Call(`_rts2_rtsModel__set_weights`, xp, weights_, covtype_, lptype_))
}

rtsModel__update_beta <- function(xp, beta_, covtype_, lptype_) {
    invisible(.Call(`_rts2_rtsModel__update_beta`, xp, beta_, covtype_, lptype_))
}

rtsModel__update_rho <- function(xp, rho_, covtype_, lptype_) {
    invisible(.Call(`_rts2_rtsModel__update_rho`, xp, rho_, covtype_, lptype_))
}

rtsModel__update_theta <- function(xp, theta_, covtype_, lptype_) {
    invisible(.Call(`_rts2_rtsModel__update_theta`, xp, theta_, covtype_, lptype_))
}

rtsModel__update_u <- function(xp, u_, covtype_, lptype_) {
    invisible(.Call(`_rts2_rtsModel__update_u`, xp, u_, covtype_, lptype_))
}

rtsModel__use_attenuation <- function(xp, use_, covtype_, lptype_) {
    invisible(.Call(`_rts2_rtsModel__use_attenuation`, xp, use_, covtype_, lptype_))
}

rtsModel__get_W <- function(xp, covtype_, lptype_) {
    .Call(`_rts2_rtsModel__get_W`, xp, covtype_, lptype_)
}

rtsModel__ml_theta <- function(xp, covtype_, lptype_) {
    invisible(.Call(`_rts2_rtsModel__ml_theta`, xp, covtype_, lptype_))
}

rtsModel__ml_beta <- function(xp, covtype_, lptype_) {
    invisible(.Call(`_rts2_rtsModel__ml_beta`, xp, covtype_, lptype_))
}

rtsModel__ml_rho <- function(xp, covtype_, lptype_) {
    invisible(.Call(`_rts2_rtsModel__ml_rho`, xp, covtype_, lptype_))
}

rtsModel__laplace_ml_beta_u <- function(xp, covtype_, lptype_) {
    invisible(.Call(`_rts2_rtsModel__laplace_ml_beta_u`, xp, covtype_, lptype_))
}

rtsModel__laplace_ml_theta <- function(xp, covtype_, lptype_) {
    invisible(.Call(`_rts2_rtsModel__laplace_ml_theta`, xp, covtype_, lptype_))
}

rtsModel__laplace_ml_beta_theta <- function(xp, covtype_, lptype_) {
    invisible(.Call(`_rts2_rtsModel__laplace_ml_beta_theta`, xp, covtype_, lptype_))
}

rtsModel__nr_beta <- function(xp, covtype_, lptype_) {
    invisible(.Call(`_rts2_rtsModel__nr_beta`, xp, covtype_, lptype_))
}

rtsModel__laplace_nr_beta_u <- function(xp, covtype_, lptype_) {
    invisible(.Call(`_rts2_rtsModel__laplace_nr_beta_u`, xp, covtype_, lptype_))
}

rtsModel__Sigma <- function(xp, inverse, covtype_, lptype_) {
    .Call(`_rts2_rtsModel__Sigma`, xp, inverse, covtype_, lptype_)
}

rtsModel__information_matrix <- function(xp, covtype_, lptype_) {
    .Call(`_rts2_rtsModel__information_matrix`, xp, covtype_, lptype_)
}

rtsModel__u <- function(xp, scaled_, covtype_, lptype_) {
    .Call(`_rts2_rtsModel__u`, xp, scaled_, covtype_, lptype_)
}

rtsModel__X <- function(xp, covtype_, lptype_) {
    .Call(`_rts2_rtsModel__X`, xp, covtype_, lptype_)
}

rtsModel__set_trace <- function(xp, trace_, covtype_, lptype_) {
    invisible(.Call(`_rts2_rtsModel__set_trace`, xp, trace_, covtype_, lptype_))
}

rtsModel__get_beta <- function(xp, covtype_, lptype_) {
    .Call(`_rts2_rtsModel__get_beta`, xp, covtype_, lptype_)
}

rtsModel__get_theta <- function(xp, covtype_, lptype_) {
    .Call(`_rts2_rtsModel__get_theta`, xp, covtype_, lptype_)
}

rtsModel__ZL <- function(xp, covtype_, lptype_) {
    .Call(`_rts2_rtsModel__ZL`, xp, covtype_, lptype_)
}

rtsModel__D <- function(xp, covtype_, lptype_) {
    .Call(`_rts2_rtsModel__D`, xp, covtype_, lptype_)
}

rtsModel__xb <- function(xp, covtype_, lptype_) {
    .Call(`_rts2_rtsModel__xb`, xp, covtype_, lptype_)
}

rtsModel_nngp__A <- function(ptr_, lptype_) {
    .Call(`_rts2_rtsModel_nngp__A`, ptr_, lptype_)
}

rtsModel_nngp__D <- function(ptr_, lptype_) {
    .Call(`_rts2_rtsModel_nngp__D`, ptr_, lptype_)
}

rtsModel_nngp__submatrix <- function(ptr_, lptype_, i_) {
    .Call(`_rts2_rtsModel_nngp__submatrix`, ptr_, lptype_, i_)
}

rtsModel_cov__log_likelihood <- function(xp, covtype_, lptype_, u_) {
    .Call(`_rts2_rtsModel_cov__log_likelihood`, xp, covtype_, lptype_, u_)
}

rtsModel_cov__set_sparse <- function(ptr_, lptype_, sparse_) {
    invisible(.Call(`_rts2_rtsModel_cov__set_sparse`, ptr_, lptype_, sparse_))
}

rtsModel__aic <- function(xp, covtype_, lptype_) {
    .Call(`_rts2_rtsModel__aic`, xp, covtype_, lptype_)
}

rtsModel__beta_parameter_names <- function(xp, covtype_, lptype_) {
    .Call(`_rts2_rtsModel__beta_parameter_names`, xp, covtype_, lptype_)
}

rtsModel__theta_parameter_names <- function(xp, covtype_, lptype_) {
    .Call(`_rts2_rtsModel__theta_parameter_names`, xp, covtype_, lptype_)
}

rtsModel__infomat_theta <- function(xp, covtype_, lptype_) {
    .Call(`_rts2_rtsModel__infomat_theta`, xp, covtype_, lptype_)
}

rtsModel__region_intensity <- function(xp, covtype_, lptype_) {
    .Call(`_rts2_rtsModel__region_intensity`, xp, covtype_, lptype_)
}

rtsModel__region_grid_xb <- function(xp, covtype_) {
    .Call(`_rts2_rtsModel__region_grid_xb`, xp, covtype_)
}

rtsModel__grid_to_region <- function(xp, u_) {
    .Call(`_rts2_rtsModel__grid_to_region`, xp, u_)
}

rtsModel__predict <- function(xp, newdata_, newoffset_, m, covtype_, lptype_) {
    .Call(`_rts2_rtsModel__predict`, xp, newdata_, newoffset_, m, covtype_, lptype_)
}

max_dist <- function(x) {
    .Call(`_rts2_max_dist`, x)
}

semivariogram <- function(x, offs, y, nbins) {
    .Call(`_rts2_semivariogram`, x, offs, y, nbins)
}

